---
version: "3.8"
services:
  movies:
    image: srinadhgoud/paytmmovies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: srinadhgoud/paytmtrain:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: srinadhgoud/paytmrecharge:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: srinadhgoud/paytmdth:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
