---
version: "3.8"
services:
  movies:
    image: fayaz1993/paytm-movie-pay:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: fayaz1993/paytm-train-pay:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: fayaz1993/paytm-dth-pay:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: fayaz1993/paytm-recharge-pay:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
